[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv", "libGL", "glib", "zlib"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && gunicorn Traffic.wsgi --bind 0.0.0.0:$PORT"
